name: Testing

# This workflows simulates an environment to test the entire application using unit testing, integration testing, and system testing.
on: [push]

jobs:
  publish:
    name: Publish the release version
    runs-on: ubuntu-latest
    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run preview
          wait-on: 'http://localhost:3000'
          browser: chrome

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
          verbose: true
