name: E2E on Chrome

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install frontend dependencies and start server
        working-directory: ./frontend
        run: |
          npm install &&
          npm start & &&
          timeout 30s bash -c 'until nc -z localhost 3000; do sleep 1; done'

      - name: Create and activate python environment, install backend dependencies, and start server
        working-directory: ./backend
        run: |
          python -m venv venv &&
          source venv/bin/activate &&
          pip install -r requirements.txt &&
          python manage.py runserver &

      - name: Install Cypress and run tests
        working-directory: ./frontend
        run: |
          npm install cypress --save-dev &&
          npx cypress run

      - name: Run Unit tests Django
        working-directory: ./backend
        run: python manage.py test

      
