name: E2E on Chrome

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Navigate to frontend directory
        run: cd frontend

      - name: Install dependencies
        run: npm install

      - name: Run frontend build
        run: npm run build

      - name: Start frontend server
        run: npm start &

      - name: Wait for frontend server to start
        run: |
          timeout 30s bash -c 'until nc -z localhost 3000; do sleep 1; done'

      - name: Run Cypress tests
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          start: npm start
          wait-on: "http://localhost:3000"


