name: E2E on Chrome

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install frontend dependencies
        working-directory: THE-390/frontend
        run: |
          npm install
          npm start &
          timeout 30s bash -c 'until nc -z localhost 3000; do sleep 1; done'

      - name: Create python environment locally 
        working-directory: THE-390/backend
        run: python -m venv venv

      - name: Activate python environment
        run: source THE-390/backend/venv/bin/activate

      - name: Install backend dependencies
        working-directory: THE-390/backend
        run: pip install -r requirements.txt

      - name: Start backend server
        working-directory: THE-390/backend
        run: python manage.py runserver &

      - name: Install Cypress
        working-directory: THE-390/frontend
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        working-directory: THE-390/frontend
        run: npx cypress run

      - name: Run Unit tests Django
        working-directory: THE-390/backend
        run: python manage.py test


      
