name: E2E on Chrome

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Navigate to frontend directory
        run: cd frontend

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Start frontend server
        working-directory: ./frontend
        run: npm start 

      - name: Wait for frontend server to start
        run: |
          timeout 30s bash -c 'until nc -z localhost 3000; do sleep 1; done'

      - name: Run Cypress tests
        run: npx cypress run


